"""allow null values on training_session

Revision ID: 01504de4e2f5
Revises: 5dd35de4d001
Create Date: 2018-03-09 21:42:53.304118

"""

# revision identifiers, used by Alembic.
revision = '01504de4e2f5'
down_revision = '5dd35de4d001'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_session', 'session_lead_trainer',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('training_session', 'session_topic_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_session', 'session_topic_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('training_session', 'session_lead_trainer',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
