"""Add Country fields to training plus status

Revision ID: 057f277c3729
Revises: 26c852f29cb7
Create Date: 2018-06-06 11:48:56.570579

"""

# revision identifiers, used by Alembic.
revision = '057f277c3729'
down_revision = '26c852f29cb7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_questions', sa.Column('country', sa.String(length=20), server_default=sa.text(u"'UG'"), nullable=False))
    op.add_column('exam_results', sa.Column('country', sa.String(length=20), server_default=sa.text(u"'UG'"), nullable=False))
    op.add_column('exam_status', sa.Column('country', sa.String(length=20), server_default=sa.text(u"'UG'"), nullable=False))
    op.add_column('exam_trainings', sa.Column('country', sa.String(length=20), server_default=sa.text(u"'UG'"), nullable=False))
    op.add_column('exam_trainings', sa.Column('exam_status_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_exam_trainings_exam_status_id'), 'exam_trainings', ['exam_status_id'], unique=False)
    op.create_foreign_key(None, 'exam_trainings', 'exam_status', ['exam_status_id'], ['id'])
    op.add_column('question_choices', sa.Column('country', sa.String(length=20), server_default=sa.text(u"'KE'"), nullable=False))
    op.add_column('question_topics', sa.Column('country', sa.String(length=20), server_default=sa.text(u"'KE'"), nullable=False))
    op.add_column('questions', sa.Column('country', sa.String(length=20), server_default=sa.text(u"'KE'"), nullable=False))
    op.add_column('training_exams', sa.Column('country', sa.String(length=20), server_default=sa.text(u"'KE'"), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_exams', 'country')
    op.drop_column('questions', 'country')
    op.drop_column('question_topics', 'country')
    op.drop_column('question_choices', 'country')
    op.drop_constraint(None, 'exam_trainings', type_='foreignkey')
    op.drop_index(op.f('ix_exam_trainings_exam_status_id'), table_name='exam_trainings')
    op.drop_column('exam_trainings', 'exam_status_id')
    op.drop_column('exam_trainings', 'country')
    op.drop_column('exam_status', 'country')
    op.drop_column('exam_results', 'country')
    op.drop_column('exam_questions', 'country')
    # ### end Alembic commands ###
