"""add foreignKeys

Revision ID: 0591eed58892
Revises: 5efc97a3ae33
Create Date: 2017-08-15 14:54:49.964629

"""

# revision identifiers, used by Alembic.
revision = '0591eed58892'
down_revision = '5efc97a3ae33'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partner_cu', 'partner_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.create_index(op.f('ix_partner_cu_community_unit_id'), 'partner_cu', ['community_unit_id'], unique=False)
    op.create_index(op.f('ix_partner_cu_partner_id'), 'partner_cu', ['partner_id'], unique=False)
    op.create_index(op.f('ix_partner_cu_village_id'), 'partner_cu', ['village_id'], unique=False)
    op.create_foreign_key(None, 'partner_cu', 'community_unit', ['community_unit_id'], ['id'])
    op.create_foreign_key(None, 'partner_cu', 'partner', ['partner_id'], ['id'])
    
    # op.create_foreign_key(None, 'partner_cu', 'village', ['village_id'], ['id'])
    
    # op.drop_index(op.f('ix_subcounty_mappingId'), table_name='subcounty')
    # op.drop_index(op.f('ix_subcounty_countyID'), table_name='subcounty')
    
    op.create_index(op.f('ix_subcounty_countyID'), 'subcounty', ['countyID'], unique=False)
    op.create_index(op.f('ix_subcounty_mappingId'), 'subcounty', ['mappingId'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subcounty_mappingId'), table_name='subcounty')
    op.drop_index(op.f('ix_subcounty_countyID'), table_name='subcounty')
    op.drop_constraint(None, 'partner_cu', type_='foreignkey')
    op.drop_constraint(None, 'partner_cu', type_='foreignkey')
    op.drop_constraint(None, 'partner_cu', type_='foreignkey')
    op.drop_index(op.f('ix_partner_cu_village_id'), table_name='partner_cu')
    op.drop_index(op.f('ix_partner_cu_partner_id'), table_name='partner_cu')
    op.drop_index(op.f('ix_partner_cu_community_unit_id'), table_name='partner_cu')
    op.alter_column('partner_cu', 'partner_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
