"""aggregating all training models

Revision ID: 0af760ae88f4
Revises: 8ec47b658695
Create Date: 2017-09-11 16:20:36.492417

"""

# revision identifiers, used by Alembic.
revision = '0af760ae88f4'
down_revision = '8ec47b658695'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_topic',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=70), nullable=False),
        sa.Column('country', sa.String(length=20), nullable=True),
        sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
        sa.Column('date_added', sa.DateTime(), nullable=False),
        sa.Column('added_by', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['added_by'], [u'users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_topic_added_by'), 'session_topic', ['added_by'], unique=False)

    op.create_table('training_venues',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=True),
        sa.Column('mapping', sa.String(length=64), nullable=True),
        sa.Column('lat', sa.Float(), server_default=sa.text(u'0'), nullable=False),
        sa.Column('lon', sa.Float(), server_default=sa.text(u'0'), nullable=False),
        sa.Column('inspected', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
        sa.Column('country', sa.String(length=20), nullable=True),
        sa.Column('selected', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
        sa.Column('capacity', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
        sa.Column('date_added', sa.DateTime(), nullable=False),
        sa.Column('added_by', sa.Integer(), nullable=True),
        sa.Column('client_time', sa.Numeric(), nullable=True),
        sa.Column('meta_data', sa.Text(), nullable=True),
        sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
        sa.ForeignKeyConstraint(['mapping'], [u'mapping.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('training_classes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('training_id', sa.String(length=64), nullable=False),
        sa.Column('class_name', sa.String(length=20), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=False),
        sa.Column('client_time', sa.Numeric(), nullable=True),
        sa.Column('date_created', sa.DateTime(), nullable=False),
        sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
        sa.Column('country', sa.String(length=20), server_default=sa.text(u"'UG'"), nullable=False),
        sa.ForeignKeyConstraint(['created_by'], [u'users.id'], ),
        sa.ForeignKeyConstraint(['training_id'], [u'training.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_classes_created_by'), 'training_classes', ['created_by'], unique=False)
    op.create_index(op.f('ix_training_classes_training_id'), 'training_classes', ['training_id'], unique=False)

    op.create_table('trainees',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('registration_id', sa.String(length=64), nullable=False),
        sa.Column('class_id', sa.Integer(), nullable=False),
        sa.Column('training_id', sa.String(length=64), nullable=False),
        sa.Column('country', sa.String(length=20), server_default=sa.text(u"'UG'"), nullable=False),
        sa.Column('date_created', sa.DateTime(), nullable=False),
        sa.Column('added_by', sa.Integer(), nullable=False),
        sa.Column('client_time', sa.Numeric(), nullable=True),
        sa.Column('branch', sa.Integer(), nullable=False),
        sa.Column('cohort', sa.Integer(), nullable=False),
        sa.Column('chp_code', sa.String(length=45), nullable=False),
        sa.ForeignKeyConstraint(['added_by'], [u'users.id'], ),
        sa.ForeignKeyConstraint(['branch'], [u'branch.id'], ),
        sa.ForeignKeyConstraint(['class_id'], [u'training_classes.id'], ),
        sa.ForeignKeyConstraint(['cohort'], [u'cohort.id'], ),
        sa.ForeignKeyConstraint(['registration_id'], [u'registrations.id'], ),
        sa.ForeignKeyConstraint(['training_id'], [u'training.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainees_added_by'), 'trainees', ['added_by'], unique=False)
    op.create_index(op.f('ix_trainees_branch'), 'trainees', ['branch'], unique=False)
    op.create_index(op.f('ix_trainees_class_id'), 'trainees', ['class_id'], unique=False)
    op.create_index(op.f('ix_trainees_cohort'), 'trainees', ['cohort'], unique=False)
    op.create_index(op.f('ix_trainees_registration_id'), 'trainees', ['registration_id'], unique=False)
    op.create_index(op.f('ix_trainees_training_id'), 'trainees', ['training_id'], unique=False)
    op.drop_table('chp')


    # Branch table
    op.alter_column(u'branch', 'name', new_column_name='branch_name')
    op.alter_column(u'branch',
                    'lat',
                    type_=sa.Float,
                    existing_type=sa.String(length=45),
                    postgresql_using='lat::text::double precision'
    )
    op.alter_column(u'branch',
                    'lon',
                    type_=sa.Float,
                    existing_type=sa.String(length=45),
                    postgresql_using='lon::text::double precision'
                    )
    op.add_column(u'branch',
                  sa.Column('branch_code',
                            sa.String(length=45),
                            nullable=True
                            )
                  )
    op.add_column(u'branch',
                  sa.Column('mapping_id',
                            sa.String(length=64),
                            nullable=True
                            )
                  )

    op.drop_index('ix_branch_location_id', table_name='branch')
    op.drop_constraint(u'branch_location_id_fkey', 'branch', type_='foreignkey')
    op.create_foreign_key(None, 'branch', 'mapping', ['mapping_id'], ['id'])
    op.drop_column(u'branch', 'location_id')

    # cohort
    op.add_column(u'cohort', sa.Column('cohort_name', sa.String(length=45), nullable=True))

    
    # training
    
    
    op.add_column(u'training', sa.Column('training_venue_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_training_training_venue_id'), 'training', ['training_venue_id'], unique=False)
    op.create_foreign_key(None, 'training', 'training_venues', ['training_venue_id'], ['id'])

    # training session
    op.add_column(u'training_session', sa.Column('class_id', sa.Integer(), nullable=False))
    op.add_column(u'training_session', sa.Column('session_end_time', sa.Numeric(), nullable=True))
    op.add_column(u'training_session', sa.Column('session_lead_trainer', sa.Integer(), nullable=False))
    op.add_column(u'training_session', sa.Column('session_start_time', sa.Numeric(), nullable=True))
    op.add_column(u'training_session', sa.Column('session_topic_id', sa.Integer(), nullable=False))
    op.add_column(u'training_session', sa.Column('trainer_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_training_session_class_id'), 'training_session', ['class_id'], unique=False)
    op.create_index(op.f('ix_training_session_session_lead_trainer'), 'training_session', ['session_lead_trainer'], unique=False)
    op.create_index(op.f('ix_training_session_session_topic_id'), 'training_session', ['session_topic_id'], unique=False)
    op.create_index(op.f('ix_training_session_trainer_id'), 'training_session', ['trainer_id'], unique=False)
    op.create_foreign_key(None, 'training_session', 'users', ['session_lead_trainer'], ['id'])
    op.create_foreign_key(None, 'training_session', 'session_topic', ['session_topic_id'], ['id'])
    op.create_foreign_key(None, 'training_session', 'users', ['trainer_id'], ['id'])
    op.create_foreign_key(None, 'training_session', 'training_classes', ['class_id'], ['id'])

    # training trainers
    op.add_column(u'training_trainers', sa.Column('class_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_training_trainers_class_id'), 'training_trainers', ['class_id'], unique=False)
    op.create_foreign_key(None, 'training_trainers', 'training_classes', ['class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # training trainers
    op.drop_constraint(None, 'training_trainers', type_='foreignkey')
    op.drop_constraint(None, 'training_trainers', type_='foreignkey')
    op.drop_index(op.f('ix_training_trainers_training_role_id'), table_name='training_trainers')
    op.drop_index(op.f('ix_training_trainers_class_id'), table_name='training_trainers')
    op.drop_column(u'training_trainers', 'training_role_id')
    op.drop_column(u'training_trainers', 'class_id')

    # training session
    op.drop_constraint(None, 'training_session', type_='foreignkey')
    op.drop_constraint(None, 'training_session', type_='foreignkey')
    op.drop_constraint(None, 'training_session', type_='foreignkey')
    op.drop_constraint(None, 'training_session', type_='foreignkey')
    op.drop_index(op.f('ix_training_session_trainer_id'), table_name='training_session')
    op.drop_index(op.f('ix_training_session_session_topic_id'), table_name='training_session')
    op.drop_index(op.f('ix_training_session_session_lead_trainer'), table_name='training_session')
    op.drop_index(op.f('ix_training_session_class_id'), table_name='training_session')
    op.drop_column(u'training_session', 'trainer_id')
    op.drop_column(u'training_session', 'session_topic_id')
    op.drop_column(u'training_session', 'session_start_time')
    op.drop_column(u'training_session', 'session_lead_trainer')
    op.drop_column(u'training_session', 'session_end_time')
    op.drop_column(u'training_session', 'class_id')

    # training
    op.drop_constraint(None, 'training', type_='foreignkey')
    op.drop_index(op.f('ix_training_training_venue_id'), table_name='training')
    op.drop_column(u'training', 'training_venue_id')
   

    # cohort
    op.drop_column(u'cohort', 'cohort_name')

    # branch
    op.alter_column(u'branch', 'branch_name', new_column_name='name')
    op.add_column(u'branch', sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'branch', type_='foreignkey')
    op.create_foreign_key(u'branch_location_id_fkey', 'branch', 'location', ['location_id'], ['id'])
    op.create_index('ix_branch_location_id', 'branch', ['location_id'], unique=False)
    op.drop_column(u'branch', 'mapping_id')
    op.drop_column(u'branch', 'branch_code')
    op.alter_column(u'branch', 'lat', type_=sa.String(length=45), existing_type=sa.Float)
    op.alter_column(u'branch', 'lon', type_=sa.String(length=45), existing_type=sa.Float)

    op.create_table('chp',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('f_name', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
        sa.Column('l_name', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
        sa.Column('m_name', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
        sa.Column('cohort_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('phone', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
        sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('chp_id', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
        sa.Column('archived', sa.INTEGER(), server_default=sa.text(u'0'), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['branch_id'], [u'branch.id'], name=u'chp_branch_id_fkey'),
        sa.ForeignKeyConstraint(['cohort_id'], [u'cohort.id'], name=u'chp_cohort_id_fkey'),
        sa.ForeignKeyConstraint(['location_id'], [u'location.id'], name=u'chp_location_id_fkey'),
        sa.PrimaryKeyConstraint('id', name=u'chp_pkey')
    )

    # trainees
    op.drop_index(op.f('ix_trainees_training_id'), table_name='trainees')
    op.drop_index(op.f('ix_trainees_registration_id'), table_name='trainees')
    op.drop_index(op.f('ix_trainees_cohort'), table_name='trainees')
    op.drop_index(op.f('ix_trainees_class_id'), table_name='trainees')
    op.drop_index(op.f('ix_trainees_branch'), table_name='trainees')
    op.drop_index(op.f('ix_trainees_added_by'), table_name='trainees')
    op.drop_table('trainees')

    # training classes
    op.drop_index(op.f('ix_training_classes_training_id'), table_name='training_classes')
    op.drop_index(op.f('ix_training_classes_created_by'), table_name='training_classes')
    op.drop_table('training_classes')

    # training venues
    op.drop_table('training_venues')

    # session topic
    op.drop_index(op.f('ix_session_topic_added_by'), table_name='session_topic')
    op.drop_table('session_topic')
    # ### end Alembic commands ###
