"""change Partner_cu to Parner Activity table

Revision ID: 0cc6576e18f0
Revises: dbe50cfb9d16
Create Date: 2017-08-17 13:32:22.902717

"""

# revision identifiers, used by Alembic.
revision = '0cc6576e18f0'
down_revision = 'dbe50cfb9d16'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('partner_cu',
                  sa.Column('county_id', sa.String(length=64), nullable=True))
    op.add_column('partner_cu',
                  sa.Column('sub_county_id', sa.String(length=64), nullable=True))
    op.add_column('partner_cu',
                  sa.Column('parish_id', sa.String(length=64), nullable=True))
    op.add_column('partner_cu',
                  sa.Column('doing_mhealth', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True))
    op.add_column('partner_cu',
                  sa.Column('doing_iccm', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True))
    op.add_column('partner_cu',
                  sa.Column('giving_free_drugs', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True))
    op.add_column('partner_cu',
                  sa.Column('giving_stipend', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True))
    op.add_column('partner_cu',
                  sa.Column('activities', sa.Text(), nullable=True))
    
    op.rename_table('partner_cu','partner_activity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partner_activity', 'county_id')
    op.drop_column('partner_activity', 'sub_county_id')
    op.drop_column('partner_activity', 'parish_id')
    op.drop_column('partner_activity', 'doing_mhealth')
    op.drop_column('partner_activity', 'doing_iccm')
    op.drop_column('partner_activity', 'giving_free_drugs')
    op.drop_column('partner_activity', 'giving_stipend')
    op.drop_column('partner_activity', 'activities')

    op.rename_table('partner_activity', 'partner_cu')
    # ### end Alembic commands ###
