"""Add ChewID to Registration Model

Revision ID: 0fbe8d283dee
Revises: 6ebcc201a99f
Create Date: 2017-09-19 07:03:55.377832

"""

# revision identifiers, used by Alembic.
revision = '0fbe8d283dee'
down_revision = '6ebcc201a99f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('referral_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_registrations_referral_id'), 'registrations', ['referral_id'], unique=False)
    op.create_foreign_key(None, 'registrations', 'referrals', ['referral_id'], ['id'])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.drop_index(op.f('ix_registrations_referral_id'), table_name='registrations')
    op.drop_column('registrations', 'referral_id')
    # ### end Alembic commands ###
