"""Added district_id to branch

Revision ID: 1b3aaa63ccb8
Revises: ac5ea11816da
Create Date: 2019-09-23 12:20:17.260341

"""

# revision identifiers, used by Alembic.
revision = '1b3aaa63ccb8'
down_revision = 'ac5ea11816da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch', sa.Column('district_id', sa.String(length=65), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branch', 'district_id')
    # ### end Alembic commands ###
