"""empty message

Revision ID: 1b90e26ba1d3
Revises: None
Create Date: 2017-06-19 14:30:51.150714

"""

# revision identifiers, used by Alembic.
revision = '1b90e26ba1d3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('level_type', sa.String(length=45), nullable=True),
    sa.Column('hierachy', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('country', sa.String(length=45), server_default=sa.text(u"'UG'"), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geo_name', sa.String(length=20), nullable=True),
    sa.Column('geo_code', sa.String(length=20), nullable=True),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('geo_name')
    )
    op.create_table('gps_data',
    sa.Column('id', sa.String(length=45), nullable=False),
    sa.Column('chp_phone', sa.String(length=45), nullable=True),
    sa.Column('record_uuid', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('client_time', sa.Numeric(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('lat', sa.Float(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('lon', sa.Float(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('gps_on', sa.Boolean(), nullable=True),
    sa.Column('activity_type', sa.String(length=45), nullable=True),
    sa.Column('time_to_resolve', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=65), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('lat', sa.String(length=45), nullable=True),
    sa.Column('lon', sa.String(length=45), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('admin_name', sa.String(length=45), nullable=True),
    sa.Column('code', sa.String(length=45), nullable=True),
    sa.Column('country', sa.String(length=45), nullable=True),
    sa.Column('polygon', sa.Text(), nullable=True),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.ForeignKeyConstraint(['parent'], [u'location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_parent'), 'location', ['parent'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('user_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('branch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('lat', sa.String(length=45), nullable=True),
    sa.Column('lon', sa.String(length=45), nullable=True),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], [u'location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branch_location_id'), 'branch', ['location_id'], unique=False)
    op.create_table('education_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('education_id', sa.Integer(), nullable=True),
    sa.Column('level_name', sa.String(length=45), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.ForeignKeyConstraint(['education_id'], [u'education.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_level_education_id'), 'education_level', ['education_id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('phone', sa.String(length=45), nullable=True),
    sa.Column('title', sa.String(length=45), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], [u'location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_location_id'), 'referrals', ['location_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('app_name', sa.String(length=128), nullable=True),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('avatar_hash', sa.String(length=32), nullable=True),
    sa.Column('geo_id', sa.Integer(), nullable=True),
    sa.Column('user_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['geo_id'], ['geos.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('village',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=65), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('lat', sa.String(length=45), nullable=True),
    sa.Column('lon', sa.String(length=45), nullable=True),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], [u'location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_village_location_id'), 'village', ['location_id'], unique=False)
    op.create_table('cohort',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohort_number', sa.String(length=45), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], [u'branch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cohort_branch_id'), 'cohort', ['branch_id'], unique=False)
    op.create_table('mapping',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('county', sa.String(length=64), nullable=True),
    sa.Column('subcounty', sa.String(length=64), nullable=True),
    sa.Column('district', sa.String(length=64), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=False),
    sa.Column('contact_person', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('synced', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('client_time', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], [u'users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mapping_added_by'), 'mapping', ['added_by'], unique=False)
    op.create_table('recruitments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('lat', sa.String(length=128), nullable=True),
    sa.Column('lon', sa.String(length=128), nullable=True),
    sa.Column('subcounty', sa.String(length=128), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('county', sa.String(length=128), nullable=True),
    sa.Column('division', sa.String(length=128), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('client_time', sa.Numeric(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('synced', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], [u'users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruitments_added_by'), 'recruitments', ['added_by'], unique=False)
    op.create_table('registrations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=6), nullable=True),
    sa.Column('recruitment', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=16), nullable=True),
    sa.Column('dob', sa.Numeric(), nullable=True),
    sa.Column('district', sa.String(length=64), nullable=True),
    sa.Column('subcounty', sa.String(length=64), nullable=True),
    sa.Column('division', sa.String(length=64), nullable=True),
    sa.Column('village', sa.String(length=64), nullable=True),
    sa.Column('feature', sa.String(length=128), nullable=True),
    sa.Column('english', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('date_moved', sa.Integer(), nullable=True),
    sa.Column('languages', sa.String(length=128), nullable=True),
    sa.Column('brac', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('brac_chp', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('education', sa.Integer(), nullable=True),
    sa.Column('occupation', sa.String(length=128), nullable=True),
    sa.Column('community_membership', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('proceed', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('client_time', sa.Numeric(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('synced', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('chew_name', sa.String(length=128), nullable=True),
    sa.Column('chew_number', sa.String(length=128), nullable=True),
    sa.Column('ward', sa.String(length=128), nullable=True),
    sa.Column('cu_name', sa.String(length=128), nullable=True),
    sa.Column('link_facility', sa.String(length=128), nullable=True),
    sa.Column('households', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('trainings', sa.String(length=128), nullable=True),
    sa.Column('is_chv', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('is_gok_trained', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('referral', sa.String(length=128), nullable=True),
    sa.Column('referral_number', sa.String(length=128), nullable=True),
    sa.Column('referral_title', sa.String(length=128), nullable=True),
    sa.Column('vht', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('parish', sa.String(length=128), nullable=True),
    sa.Column('financial_accounts', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('recruitment_transport', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('branch_transport', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['education'], [u'education.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registrations_added_by'), 'registrations', ['added_by'], unique=False)
    op.create_index(op.f('ix_registrations_education'), 'registrations', ['education'], unique=False)
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(length=45), nullable=True),
    sa.Column('m_name', sa.String(length=45), nullable=True),
    sa.Column('l_name', sa.String(length=45), nullable=True),
    sa.Column('referral_id', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('recruitment_id', sa.String(length=64), nullable=True),
    sa.Column('education_id', sa.Integer(), nullable=True),
    sa.Column('edu_level_id', sa.Integer(), nullable=True),
    sa.Column('vht', sa.Integer(), nullable=True),
    sa.Column('maths', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('english', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('about_you', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('total_score', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('gender', sa.String(length=2), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('landmark', sa.String(length=45), nullable=True),
    sa.Column('date_moved', sa.DateTime(), nullable=True),
    sa.Column('languages', sa.String(length=245), nullable=True),
    sa.Column('worked_brac', sa.Integer(), nullable=True),
    sa.Column('brac_chp', sa.Integer(), nullable=True),
    sa.Column('community_membership', sa.String(length=245), nullable=True),
    sa.Column('read_english', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('application_score', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('testing', sa.Integer(), nullable=True),
    sa.Column('niaje', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['edu_level_id'], [u'education_level.id'], ),
    sa.ForeignKeyConstraint(['education_id'], [u'education.id'], ),
    sa.ForeignKeyConstraint(['location_id'], [u'location.id'], ),
    sa.ForeignKeyConstraint(['recruitment_id'], [u'recruitments.id'], ),
    sa.ForeignKeyConstraint(['referral_id'], [u'referrals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_edu_level_id'), 'application', ['edu_level_id'], unique=False)
    op.create_index(op.f('ix_application_education_id'), 'application', ['education_id'], unique=False)
    op.create_index(op.f('ix_application_location_id'), 'application', ['location_id'], unique=False)
    op.create_index(op.f('ix_application_recruitment_id'), 'application', ['recruitment_id'], unique=False)
    op.create_index(op.f('ix_application_referral_id'), 'application', ['referral_id'], unique=False)
    op.create_table('chp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(length=45), nullable=True),
    sa.Column('l_name', sa.String(length=45), nullable=True),
    sa.Column('m_name', sa.String(length=45), nullable=True),
    sa.Column('cohort_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=45), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('chp_id', sa.String(length=45), nullable=True),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], [u'branch.id'], ),
    sa.ForeignKeyConstraint(['cohort_id'], [u'cohort.id'], ),
    sa.ForeignKeyConstraint(['location_id'], [u'location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chp_branch_id'), 'chp', ['branch_id'], unique=False)
    op.create_index(op.f('ix_chp_cohort_id'), 'chp', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_chp_location_id'), 'chp', ['location_id'], unique=False)
    op.create_table('exams',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('applicant', sa.String(length=64), nullable=True),
    sa.Column('recruitment', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('math', sa.Float(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('personality', sa.Float(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('english', sa.Float(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('client_time', sa.Numeric(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('synced', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['applicant'], [u'registrations.id'], ),
    sa.ForeignKeyConstraint(['recruitment'], [u'recruitments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_added_by'), 'exams', ['added_by'], unique=False)
    op.create_index(op.f('ix_exams_applicant'), 'exams', ['applicant'], unique=False)
    op.create_index(op.f('ix_exams_recruitment'), 'exams', ['recruitment'], unique=False)
    op.create_table('interviews',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('applicant', sa.String(length=64), nullable=True),
    sa.Column('recruitment', sa.String(length=64), nullable=True),
    sa.Column('motivation', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('community', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('mentality', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('selling', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('health', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('investment', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('interpersonal', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('canjoin', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('commitment', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('total', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('selected', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('synced', sa.Integer(), server_default=sa.text(u"'1'"), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('client_time', sa.Numeric(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['applicant'], [u'registrations.id'], ),
    sa.ForeignKeyConstraint(['recruitment'], [u'recruitments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_added_by'), 'interviews', ['added_by'], unique=False)
    op.create_index(op.f('ix_interviews_applicant'), 'interviews', ['applicant'], unique=False)
    op.create_index(op.f('ix_interviews_recruitment'), 'interviews', ['recruitment'], unique=False)
    op.create_table('location_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('recruitment_id', sa.String(length=64), nullable=True),
    sa.Column('chps_needed', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], [u'location.id'], ),
    sa.ForeignKeyConstraint(['recruitment_id'], [u'recruitments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_targets_location_id'), 'location_targets', ['location_id'], unique=False)
    op.create_index(op.f('ix_location_targets_recruitment_id'), 'location_targets', ['recruitment_id'], unique=False)
    op.create_table('recruitment_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recruitment_id', sa.String(length=64), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], [u'location.id'], ),
    sa.ForeignKeyConstraint(['recruitment_id'], [u'recruitments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruitment_users_location_id'), 'recruitment_users', ['location_id'], unique=False)
    op.create_index(op.f('ix_recruitment_users_recruitment_id'), 'recruitment_users', ['recruitment_id'], unique=False)
    op.create_index(op.f('ix_recruitment_users_user_id'), 'recruitment_users', ['user_id'], unique=False)
    op.create_table('application_phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=45), nullable=True),
    sa.Column('main_phone', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], [u'application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_phones_application_id'), 'application_phones', ['application_id'], unique=False)
    op.create_table('selected_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('date_selected', sa.DateTime(), nullable=True),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], [u'application.id'], ),
    sa.ForeignKeyConstraint(['location_id'], [u'location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_selected_applications_application_id'), 'selected_applications', ['application_id'], unique=False)
    op.create_index(op.f('ix_selected_applications_location_id'), 'selected_applications', ['location_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_selected_applications_location_id'), table_name='selected_applications')
    op.drop_index(op.f('ix_selected_applications_application_id'), table_name='selected_applications')
    op.drop_table('selected_applications')
    op.drop_index(op.f('ix_application_phones_application_id'), table_name='application_phones')
    op.drop_table('application_phones')
    op.drop_index(op.f('ix_recruitment_users_user_id'), table_name='recruitment_users')
    op.drop_index(op.f('ix_recruitment_users_recruitment_id'), table_name='recruitment_users')
    op.drop_index(op.f('ix_recruitment_users_location_id'), table_name='recruitment_users')
    op.drop_table('recruitment_users')
    op.drop_index(op.f('ix_location_targets_recruitment_id'), table_name='location_targets')
    op.drop_index(op.f('ix_location_targets_location_id'), table_name='location_targets')
    op.drop_table('location_targets')
    op.drop_index(op.f('ix_interviews_recruitment'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_applicant'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_added_by'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_exams_recruitment'), table_name='exams')
    op.drop_index(op.f('ix_exams_applicant'), table_name='exams')
    op.drop_index(op.f('ix_exams_added_by'), table_name='exams')
    op.drop_table('exams')
    op.drop_index(op.f('ix_chp_location_id'), table_name='chp')
    op.drop_index(op.f('ix_chp_cohort_id'), table_name='chp')
    op.drop_index(op.f('ix_chp_branch_id'), table_name='chp')
    op.drop_table('chp')
    op.drop_index(op.f('ix_application_referral_id'), table_name='application')
    op.drop_index(op.f('ix_application_recruitment_id'), table_name='application')
    op.drop_index(op.f('ix_application_location_id'), table_name='application')
    op.drop_index(op.f('ix_application_education_id'), table_name='application')
    op.drop_index(op.f('ix_application_edu_level_id'), table_name='application')
    op.drop_table('application')
    op.drop_index(op.f('ix_registrations_education'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_added_by'), table_name='registrations')
    op.drop_table('registrations')
    op.drop_index(op.f('ix_recruitments_added_by'), table_name='recruitments')
    op.drop_table('recruitments')
    op.drop_index(op.f('ix_mapping_added_by'), table_name='mapping')
    op.drop_table('mapping')
    op.drop_index(op.f('ix_cohort_branch_id'), table_name='cohort')
    op.drop_table('cohort')
    op.drop_index(op.f('ix_village_location_id'), table_name='village')
    op.drop_table('village')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_referrals_location_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_education_level_education_id'), table_name='education_level')
    op.drop_table('education_level')
    op.drop_index(op.f('ix_branch_location_id'), table_name='branch')
    op.drop_table('branch')
    op.drop_table('user_types')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_location_parent'), table_name='location')
    op.drop_table('location')
    op.drop_table('gps_data')
    op.drop_table('geos')
    op.drop_table('education')
    ### end Alembic commands ###
