"""Add status to recruitment

Revision ID: 1ce224e80aeb
Revises: 4d7697c9f80f
Create Date: 2017-07-13 08:49:23.810041

"""

# revision identifiers, used by Alembic.
revision = '1ce224e80aeb'
down_revision = '4d7697c9f80f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_exams_recruitment'), 'exams', ['recruitment'], unique=False)
    op.drop_index('ix_exams_recruitment_id', table_name='exams')
    op.create_index(op.f('ix_interviews_recruitment'), 'interviews', ['recruitment'], unique=False)
    op.drop_index('ix_interviews_recruitment_id', table_name='interviews')
    op.alter_column('location', 'country',
               existing_type=sa.VARCHAR(length=45),
               nullable=True,
               existing_server_default=sa.text(u"'UG'::character varying"))
    op.add_column('recruitments', sa.Column('status', sa.String(length=64), server_default=sa.text(u"'draft'"), nullable=False))
    op.alter_column('recruitments', 'added_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_registrations_education'), 'registrations', ['education'], unique=False)
    op.create_foreign_key(None, 'registrations', 'education', ['education'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.drop_index(op.f('ix_registrations_education'), table_name='registrations')
    op.alter_column('recruitments', 'added_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('recruitments', 'status')
    op.alter_column('location', 'country',
               existing_type=sa.VARCHAR(length=45),
               nullable=False,
               existing_server_default=sa.text(u"'UG'::character varying"))
    op.create_index('ix_interviews_recruitment_id', 'interviews', ['recruitment'], unique=False)
    op.drop_index(op.f('ix_interviews_recruitment'), table_name='interviews')
    op.create_index('ix_exams_recruitment_id', 'exams', ['recruitment'], unique=False)
    op.drop_index(op.f('ix_exams_recruitment'), table_name='exams')
    ### end Alembic commands ###
