"""Allow nulls for session trainer

Revision ID: 200c406c9b7a
Revises: 01504de4e2f5
Create Date: 2018-03-13 17:12:47.968843

"""

# revision identifiers, used by Alembic.
revision = '200c406c9b7a'
down_revision = '01504de4e2f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_session', 'trainer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_session', 'trainer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
