"""Rename csv_id to batch_id

Revision ID: 26c852f29cb7
Revises: 884bd2d9d26b
Create Date: 2018-05-25 15:56:00.913010

"""

# revision identifiers, used by Alembic.
revision = '26c852f29cb7'
down_revision = '884bd2d9d26b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('batch_id', sa.String(length=64), nullable=True))
    op.drop_column('questions', 'csv_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('csv_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('questions', 'batch_id')
    # ### end Alembic commands ###
