"""add subCounty, ward, Link Facility, 
Minor updates to Location, SubCounty, Community Unit

Revision ID: 344217c7ece3
Revises: 3e99599ed0b3
Create Date: 2017-07-19 21:34:50.312098

"""

# revision identifiers, used by Alembic.
revision = '344217c7ece3'
down_revision = '3e99599ed0b3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ke_county',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=65), nullable=False),
                    sa.Column('short_code', sa.String(length=65), nullable=True),
                    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('link_facility',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('facility_name', sa.String(length=64), nullable=True),
    sa.Column('county', sa.String(length=64), nullable=True),
    sa.Column('lat', sa.Float(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('lon', sa.Float(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('subcounty', sa.String(length=64), nullable=True),
    sa.Column('client_time', sa.Numeric(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('addedby', sa.Integer(), nullable=True),
    sa.Column('mrdt_levels', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('act_levels', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('facility_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['addedby'], [u'users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_facility_addedby'), 'link_facility', ['addedby'], unique=False)
    op.create_table('subcounty',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('countyID', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('mappingId', sa.String(length=64), nullable=True),
    sa.Column('lat', sa.Float(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('lon', sa.Float(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('contactPerson', sa.String(length=64), nullable=True),
    sa.Column('contactPersonPhone', sa.String(length=64), nullable=True),
    sa.Column('mainTown', sa.String(length=64), nullable=True),
    sa.Column('countySupport', sa.String(length=64), nullable=True),
    sa.Column('subcountySupport', sa.String(length=64), nullable=True),
    sa.Column('chv_activity_level', sa.String(length=64), nullable=True),
    sa.Column('countyPopulation', sa.String(length=64), nullable=True),
    sa.Column('subCountyPopulation', sa.String(length=64), nullable=True),
    sa.Column('noOfVillages', sa.String(length=64), nullable=True),
    sa.Column('mainTownPopulation', sa.String(length=64), nullable=True),
    sa.Column('servicePopulation', sa.String(length=64), nullable=True),
    sa.Column('populationDensity', sa.String(length=64), nullable=True),
    sa.Column('transportCost', sa.String(length=64), nullable=True),
    sa.Column('majorRoads', sa.String(length=64), nullable=True),
    sa.Column('healtFacilities', sa.String(length=64), nullable=True),
    sa.Column('privateClinicsInTown', sa.String(length=64), nullable=True),
    sa.Column('privateClinicsInRadius', sa.String(length=64), nullable=True),
    sa.Column('communityUnits', sa.String(length=64), nullable=True),
    sa.Column('mainSupermarkets', sa.String(length=64), nullable=True),
    sa.Column('mainBanks', sa.String(length=64), nullable=True),
    sa.Column('anyMajorBusiness', sa.String(length=64), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('client_time', sa.Numeric(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('addedby', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['addedby'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['mappingId'], [u'mapping.id'], ),
    sa.ForeignKeyConstraint(['countyID'], [u'ke_county.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcounty_addedby'), 'subcounty', ['addedby'], unique=False)
    op.create_index(op.f('ix_subcounty_mappingId'), 'subcounty', ['mappingId'], unique=False)
    op.create_index(op.f('ix_subcounty_countyID'), 'subcounty', ['countyID'], unique=False)

    op.create_table('community_unit',
    sa.Column('id', sa.String(length=65), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('mappingid', sa.String(length=64), nullable=True),
    sa.Column('lat', sa.Float(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('lon', sa.Float(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('country', sa.String(length=45), nullable=True),
    sa.Column('subcountyid', sa.String(length=64), nullable=True),
    sa.Column('linkfacilityid', sa.String(length=64), nullable=True),
    sa.Column('areachiefname', sa.String(length=45), nullable=True),
    sa.Column('ward', sa.String(length=65), nullable=True),
    sa.Column('economicstatus', sa.String(length=45), nullable=True),
    sa.Column('privatefacilityforact', sa.String(length=45), nullable=True),
    sa.Column('privatefacilityformrdt', sa.String(length=45), nullable=True),
    sa.Column('nameofngodoingiccm', sa.String(length=45), nullable=True),
    sa.Column('nameofngodoingmhealth', sa.Text(), nullable=True),
    sa.Column('client_time', sa.Numeric(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('addedby', sa.Integer(), nullable=True),
    sa.Column('numberofchvs', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('householdperchv', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('numberofvillages', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('distancetobranch', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('transportcost', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('distancetomainroad', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('noofhouseholds', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('mohpoplationdensity', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('estimatedpopulationdensity', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('distancetonearesthealthfacility', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('actlevels', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('actprice', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('mrdtlevels', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('mrdtprice', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('noofdistibutors', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('chvstrained', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('presenceofestates', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('presenceoffactories', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('presenceofhostels', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('tradermarket', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('largesupermarket', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('ngosgivingfreedrugs', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('ngodoingiccm', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('ngodoingmhealth', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['addedby'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['linkfacilityid'], [u'link_facility.id'], ),
    sa.ForeignKeyConstraint(['mappingid'], [u'mapping.id'], ),
    sa.ForeignKeyConstraint(['subcountyid'], [u'subcounty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_unit_addedby'), 'community_unit', ['addedby'], unique=False)
    op.create_index(op.f('ix_community_unit_linkfacilityid'), 'community_unit', ['linkfacilityid'], unique=False)
    op.create_index(op.f('ix_community_unit_mappingid'), 'community_unit', ['mappingid'], unique=False)
    op.create_index(op.f('ix_community_unit_subcountyid'), 'community_unit', ['subcountyid'], unique=False)
    op.create_table('ward',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=65), nullable=False),
    sa.Column('sub_county', sa.String(length=64), nullable=True),
    sa.Column('county', sa.Integer(), nullable=True),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.ForeignKeyConstraint(['sub_county'], [u'subcounty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ward_sub_county'), 'ward', ['sub_county'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ward_sub_county'), table_name='ward')
    op.drop_table('ward')
    op.drop_index(op.f('ix_community_unit_subcountyid'), table_name='community_unit')
    op.drop_index(op.f('ix_community_unit_mappingid'), table_name='community_unit')
    op.drop_index(op.f('ix_community_unit_linkfacilityid'), table_name='community_unit')
    op.drop_index(op.f('ix_community_unit_addedby'), table_name='community_unit')
    op.drop_table('community_unit')
    op.drop_index(op.f('ix_subcounty_mappingId'), table_name='subcounty')
    op.drop_index(op.f('ix_subcounty_addedby'), table_name='subcounty')
    op.drop_table('subcounty')
    op.drop_index(op.f('ix_link_facility_addedby'), table_name='link_facility')
    op.drop_table('link_facility')
    ### end Alembic commands ###
