"""Update Referral model

Revision ID: 3e99599ed0b3
Revises: 37f0939aa4a2
Create Date: 2017-07-14 13:09:54.176747

"""

# revision identifiers, used by Alembic.
revision = '3e99599ed0b3'
down_revision = '37f0939aa4a2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
