"""Added exam training type

Revision ID: 40b608279fe1
Revises: bfcd024a1982
Create Date: 2018-07-19 23:45:06.087432

"""

# revision identifiers, used by Alembic.
revision = '40b608279fe1'
down_revision = 'bfcd024a1982'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certification_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('proportion', sa.Float(), server_default=sa.text(u"'0'"), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('country', sa.String(length=20), server_default=sa.text(u"'UG'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'exam_trainings', sa.Column('certification_type_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_exam_trainings_certification_type_id'), 'exam_trainings', ['certification_type_id'], unique=False)
    op.create_foreign_key(None, 'exam_trainings', 'certification_types', ['certification_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exam_trainings', type_='foreignkey')
    op.drop_index(op.f('ix_exam_trainings_certification_type_id'), table_name='exam_trainings')
    op.drop_column(u'exam_trainings', 'certification_type_id')
    op.drop_table('certification_types')
    # ### end Alembic commands ###
