"""add kenya county models

Revision ID: 418c7cac418b
Revises: 344217c7ece3
Create Date: 2017-07-20 07:11:42.011146

"""

# revision identifiers, used by Alembic.
revision = '418c7cac418b'
down_revision = '344217c7ece3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ke_county',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=65), nullable=False),
    sa.Column('short_code', sa.String(length=65), nullable=True),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcounty_countyID'), 'subcounty', ['countyID'], unique=False)
    op.create_foreign_key(None, 'subcounty', 'ke_county', ['countyID'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subcounty', type_='foreignkey')
    op.drop_index(op.f('ix_subcounty_countyID'), table_name='subcounty')
    op.drop_table('ke_county')
    ### end Alembic commands ###
