"""add kenya county models

Revision ID: 418c7cac418b
Revises: 344217c7ece3
Create Date: 2017-07-20 07:11:42.011146

"""

# revision identifiers, used by Alembic.
revision = '418c7cac418b'
down_revision = '344217c7ece3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
