"""change ID to integer

Revision ID: 42ca88f7ac50
Revises: 418c7cac418b
Create Date: 2017-07-20 07:15:32.526197

"""

# revision identifiers, used by Alembic.
revision = '42ca88f7ac50'
down_revision = '418c7cac418b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    def upgrade():
        ### commands auto generated by Alembic - please adjust! ###
        pass
        ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass