"""Add foreign keys to training

Revision ID: 483b042632bc
Revises: ec0f389b6dbd
Create Date: 2017-09-06 07:35:36.308423

"""

# revision identifiers, used by Alembic.
revision = '483b042632bc'
down_revision = 'ec0f389b6dbd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.create_unique_constraint(None, 'training_session', ['id'])
    op.alter_column('training_session_type', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_training_session_type_added_by', table_name='training_session_type')
    op.drop_constraint(u'training_session_type_added_by_fkey', 'training_session_type', type_='foreignkey')
    op.drop_column('training_session_type', 'date_added')
    op.drop_column('training_session_type', 'added_by')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_session_type', sa.Column('added_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('training_session_type', sa.Column('date_added', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_foreign_key(u'training_session_type_added_by_fkey', 'training_session_type', 'users', ['added_by'], ['id'])
    op.create_index('ix_training_session_type_added_by', 'training_session_type', ['added_by'], unique=False)
    op.alter_column('training_session_type', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'training_session', type_='unique')
    # ### end Alembic commands ###
