"""Add Registration Indexes

Revision ID: 4d7697c9f80f
Revises: eb4c105667a
Create Date: 2017-06-19 15:34:32.459626

"""

# revision identifiers, used by Alembic.
revision = '4d7697c9f80f'
down_revision = 'eb4c105667a'

from alembic import op
from sqlalchemy import table
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###

    op.create_index(op.f('ix_exams_recruitment'), 'exams', ['recruitment'], unique=False)
    op.drop_index('ix_exams_recruitment_id', table_name='exams')
    op.create_index(op.f('ix_interviews_recruitment'), 'interviews', ['recruitment'], unique=False)
    op.drop_index('ix_interviews_recruitment_id', table_name='interviews')
    op.alter_column('location', 'country',
               existing_type=sa.VARCHAR(length=45),
               nullable=True,
               existing_server_default=sa.text(u"'UG'::character varying"))
    op.alter_column('recruitments', 'added_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_registrations_education'), 'registrations', ['education'], unique=False)
    op.create_foreign_key(None, 'registrations', 'education', ['education'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.drop_index(op.f('ix_registrations_education'), table_name='registrations')
    op.alter_column('recruitments', 'added_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('location', 'country',
               existing_type=sa.VARCHAR(length=45),
               nullable=False,
               existing_server_default=sa.text(u"'UG'::character varying"))
    op.create_index('ix_interviews_recruitment_id', 'interviews', ['recruitment'], unique=False)
    op.drop_index(op.f('ix_interviews_recruitment'), table_name='interviews')
    op.create_index('ix_exams_recruitment_id', 'exams', ['recruitment'], unique=False)
    op.drop_index(op.f('ix_exams_recruitment'), table_name='exams')
    ### end Alembic commands ###
