"""adds video url to exam

Revision ID: 554d19fd8747
Revises: 1b3aaa63ccb8
Create Date: 2020-04-01 15:13:37.561576

"""

# revision identifiers, used by Alembic.
revision = '554d19fd8747'
down_revision = '1b3aaa63ccb8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_trainings', sa.Column('video_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_trainings', 'video_url')
    # ### end Alembic commands ###
