"""Allow nulls for TrainingSession Class_id

Revision ID: 5dd35de4d001
Revises: 641ee6100d36
Create Date: 2018-03-09 15:08:05.837912

"""

# revision identifiers, used by Alembic.
revision = '5dd35de4d001'
down_revision = '641ee6100d36'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mapping', 'added_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_mapping_added_by'), 'mapping', ['added_by'], unique=False)
    op.create_foreign_key(None, 'mapping', 'users', ['added_by'], ['id'])
    op.create_index(op.f('ix_subcounty_countyID'), 'subcounty', ['countyID'], unique=False)
    op.create_index(op.f('ix_subcounty_mappingId'), 'subcounty', ['mappingId'], unique=False)
    op.add_column('trainees', sa.Column('comment', sa.Text(), nullable=True))
    op.alter_column('trainees', 'branch',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('trainees', 'chp_code',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    op.alter_column('trainees', 'cohort',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('training_session', 'class_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_training_session_class_id', table_name='training_session')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_training_session_class_id', 'training_session', ['class_id'], unique=False)
    op.alter_column('training_session', 'class_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trainees', 'cohort',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trainees', 'chp_code',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    op.alter_column('trainees', 'branch',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('trainees', 'comment')
    op.drop_index(op.f('ix_subcounty_mappingId'), table_name='subcounty')
    op.drop_index(op.f('ix_subcounty_countyID'), table_name='subcounty')
    op.drop_constraint(None, 'mapping', type_='foreignkey')
    op.drop_index(op.f('ix_mapping_added_by'), table_name='mapping')
    op.alter_column('mapping', 'added_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
