"""add partners, partnerscu, parish models

Revision ID: 5efc97a3ae33
Revises: 42ca88f7ac50
Create Date: 2017-08-15 14:39:28.195158

"""

# revision identifiers, used by Alembic.
revision = '5efc97a3ae33'
down_revision = '42ca88f7ac50'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parish',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('parent', sa.String(length=64), nullable=True),
    sa.Column('mapping_id', sa.String(length=64), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=False),
    sa.Column('contact_person', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('synced', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('client_time', sa.Numeric(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['mapping_id'], [u'mapping.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parish_added_by'), 'parish', ['added_by'], unique=False)
    op.create_index(op.f('ix_parish_mapping_id'), 'parish', ['mapping_id'], unique=False)
    op.create_table('partner',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('contact_person', sa.String(length=64), nullable=True),
    sa.Column('contact_person_phone', sa.String(length=64), nullable=True),
    sa.Column('parent', sa.String(length=64), nullable=True),
    sa.Column('mapping_id', sa.String(length=64), nullable=True),
    sa.Column('client_time', sa.Numeric(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=False),
    sa.Column('synced', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.String(length=64), nullable=True),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['mapping_id'], [u'mapping.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_added_by'), 'partner', ['added_by'], unique=False)
    op.create_index(op.f('ix_partner_mapping_id'), 'partner', ['mapping_id'], unique=False)
    op.create_table('partner_cu',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('partner_id', sa.String(length=64), nullable=False),
    sa.Column('community_unit_id', sa.String(length=64), nullable=True),
    sa.Column('village_id', sa.String(length=64), nullable=True),
    sa.Column('mapping_id', sa.String(length=64), nullable=True),
    sa.Column('iccm_components', sa.Text(), nullable=True),
    sa.Column('client_time', sa.Numeric(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=False),
    sa.Column('synced', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.String(length=64), nullable=True),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['mapping_id'], [u'mapping.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_cu_added_by'), 'partner_cu', ['added_by'], unique=False)
    op.create_index(op.f('ix_partner_cu_mapping_id'), 'partner_cu', ['mapping_id'], unique=False)
    op.alter_column(u'link_facility', 'act_levels',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text(u'0'))
    op.alter_column(u'link_facility', 'mrdt_levels',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text(u'0'))
    op.add_column(u'mapping', sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True))
    op.drop_index('ix_subcounty_countyID', table_name='subcounty')
    op.drop_index('ix_subcounty_mappingId', table_name='subcounty')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_subcounty_mappingId', 'subcounty', ['mappingId'], unique=False)
    op.create_index('ix_subcounty_countyID', 'subcounty', ['countyID'], unique=False)
    op.drop_index(op.f('ix_subcounty_mappingId'), table_name='subcounty')
    op.drop_index(op.f('ix_subcounty_countyID'), table_name='subcounty')
    op.drop_column(u'mapping', 'archived')
    op.alter_column(u'link_facility', 'mrdt_levels',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text(u'0'))
    op.alter_column(u'link_facility', 'act_levels',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text(u'0'))
    op.drop_index(op.f('ix_partner_cu_mapping_id'), table_name='partner_cu')
    op.drop_index(op.f('ix_partner_cu_added_by'), table_name='partner_cu')
    op.drop_table('partner_cu')
    op.drop_index(op.f('ix_partner_mapping_id'), table_name='partner')
    op.drop_index(op.f('ix_partner_added_by'), table_name='partner')
    op.drop_table('partner')
    op.drop_index(op.f('ix_parish_mapping_id'), table_name='parish')
    op.drop_index(op.f('ix_parish_added_by'), table_name='parish')
    op.drop_table('parish')
    # ### end Alembic commands ###
