"""Change the Branch ID to UUID

Revision ID: 641ee6100d36
Revises: 9c48e8a72639
Create Date: 2018-03-06 12:45:07.506012

"""

# revision identifiers, used by Alembic.
revision = '641ee6100d36'
down_revision = '9c48e8a72639'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #  drop indexes
    op.drop_constraint("cohort_branch_id_fkey", 'cohort', type_='foreignkey')
    op.drop_constraint("trainees_branch_fkey", 'trainees', type_='foreignkey')
    
    op.drop_index(op.f('ix_cohort_branch_id'), table_name='cohort')
    op.drop_index(op.f('ix_trainees_branch'), table_name='trainees')
    
    
    
    op.alter_column(u'branch', 'id',
                    nullable=False,
                    type_=sa.String(length=64),
                    autoincrement=False,
                    existing_type=sa.INTEGER())
    op.alter_column(u'cohort', 'branch_id',
                    nullable=True,
                    existing_nullable=False,
                    type_=sa.String(length=64),
                    existing_type=sa.INTEGER())
    op.alter_column(u'trainees', 'branch',
                    nullable=True,
                    existing_nullable=False,
                    type_=sa.String(length=64),
                    existing_type=sa.INTEGER())
    op.alter_column(u'trainees', 'cohort',
                    nullable=True,
                    existing_nullable=False)
    op.alter_column(u'trainees', 'chp_code',
                    nullable=True,
                    existing_nullable=False)
    op.create_index(op.f('ix_cohort_branch_id'), 'cohort', ['branch_id'], unique=False)
    op.create_foreign_key("cohort_branch_id_fkey", "cohort", "branch",["branch_id"], ["id"])
    
    op.create_index(op.f('ix_trainees_branch'), 'trainees', ['branch'], unique=False)
    op.create_foreign_key("trainees_branch_fkey", "trainees", "branch",["branch"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###