"""alter referralId from int to string

Revision ID: 6ebcc201a99f
Revises: 0af760ae88f4
Create Date: 2017-09-18 12:56:38.878269

"""

# revision identifiers, used by Alembic.
revision = '6ebcc201a99f'
down_revision = '0af760ae88f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_phones')
    op.drop_table('selected_applications')
    op.drop_table('application')
    
    
    op.alter_column(u'referrals',
                    'id',
                    type_=sa.String(length=64),
                    existing_type=sa.Integer(),
                    postgresql_using='id::double precision::text')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'referrals',
                    'id',
                    type_=sa.Integer(),
                    existing_type=sa.String(length=64),
                    postgresql_using='id::text::integer')

    op.create_table('application',
                    sa.Column('id', sa.String(length=65), nullable=False),
                    sa.Column('f_name', sa.String(length=45), nullable=True),
                    sa.Column('m_name', sa.String(length=45), nullable=True),
                    sa.Column('l_name', sa.String(length=45), nullable=True),
                    sa.Column('referral_id', sa.Integer(), nullable=True),
                    sa.Column('date_added', sa.DateTime(), nullable=True),
                    sa.Column('location_id', sa.Integer(), nullable=True),
                    sa.Column('recruitment_id', sa.String(length=64), nullable=True),
                    sa.Column('education_id', sa.Integer(), nullable=True),
                    sa.Column('edu_level_id', sa.Integer(), nullable=True),
                    sa.Column('vht', sa.Integer(), nullable=True),
                    sa.Column('maths', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
                    sa.Column('english', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
                    sa.Column('about_you', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
                    sa.Column('total_score', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
                    sa.Column('gender', sa.String(length=2), nullable=True),
                    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
                    sa.Column('landmark', sa.String(length=45), nullable=True),
                    sa.Column('date_moved', sa.DateTime(), nullable=True),
                    sa.Column('languages', sa.String(length=245), nullable=True),
                    sa.Column('worked_brac', sa.Integer(), nullable=True),
                    sa.Column('brac_chp', sa.Integer(), nullable=True),
                    sa.Column('community_membership', sa.String(length=245), nullable=True),
                    sa.Column('read_english', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
                    sa.Column('application_score', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
                    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
                    sa.Column('testing', sa.Integer(), nullable=True),
                    sa.Column('niaje', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['edu_level_id'], [u'education_level.id'], ),
                    sa.ForeignKeyConstraint(['education_id'], [u'education.id'], ),
                    sa.ForeignKeyConstraint(['location_id'], [u'location.id'], ),
                    sa.ForeignKeyConstraint(['recruitment_id'], [u'recruitments.id'], ),
                    sa.ForeignKeyConstraint(['referral_id'], [u'referrals.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_application_edu_level_id'), 'application', ['edu_level_id'], unique=False)
    op.create_index(op.f('ix_application_education_id'), 'application', ['education_id'], unique=False)
    op.create_index(op.f('ix_application_location_id'), 'application', ['location_id'], unique=False)
    op.create_index(op.f('ix_application_recruitment_id'), 'application', ['recruitment_id'], unique=False)
    op.create_index(op.f('ix_application_referral_id'), 'application', ['referral_id'], unique=False)
    op.create_table('application_phones',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('application_id', sa.Integer(), nullable=True),
                    sa.Column('phone', sa.String(length=45), nullable=True),
                    sa.Column('main_phone', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
                    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
                    sa.ForeignKeyConstraint(['application_id'], [u'application.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_application_phones_application_id'), 'application_phones', ['application_id'],
                    unique=False)
    op.create_table('selected_applications',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('application_id', sa.Integer(), nullable=True),
                    sa.Column('location_id', sa.Integer(), nullable=True),
                    sa.Column('date_selected', sa.DateTime(), nullable=True),
                    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
                    sa.ForeignKeyConstraint(['application_id'], [u'application.id'], ),
                    sa.ForeignKeyConstraint(['location_id'], [u'location.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_selected_applications_application_id'), 'selected_applications', ['application_id'],
                    unique=False)
    op.create_index(op.f('ix_selected_applications_location_id'), 'selected_applications', ['location_id'],
                    unique=False)
    # ### end Alembic commands ###
