"""Add csv_id to the question model

Revision ID: 884bd2d9d26b
Revises: 5e98e45dbd08
Create Date: 2018-05-25 15:37:38.023775

"""

# revision identifiers, used by Alembic.
revision = '884bd2d9d26b'
down_revision = '5e98e45dbd08'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'exam_questions', ['id'])
    op.add_column('questions', sa.Column('csv_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'csv_id')
    op.drop_constraint(None, 'exam_questions', type_='unique')
    # ### end Alembic commands ###
