"""Training add commencement and completion dates

Revision ID: 8ec47b658695
Revises: 644a1cccf9e1
Create Date: 2017-09-06 16:25:41.053236

"""

# revision identifiers, used by Alembic.
revision = '8ec47b658695'
down_revision = '644a1cccf9e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_partner_activity_added_by'), 'partner_activity', ['added_by'], unique=False)
    op.create_index(op.f('ix_partner_activity_community_unit_id'), 'partner_activity', ['community_unit_id'], unique=False)
    op.create_index(op.f('ix_partner_activity_mapping_id'), 'partner_activity', ['mapping_id'], unique=False)
    op.create_index(op.f('ix_partner_activity_partner_id'), 'partner_activity', ['partner_id'], unique=False)
    op.create_index(op.f('ix_partner_activity_village_id'), 'partner_activity', ['village_id'], unique=False)
    op.drop_index('ix_partner_cu_added_by', table_name='partner_activity')
    op.drop_index('ix_partner_cu_community_unit_id', table_name='partner_activity')
    op.drop_index('ix_partner_cu_mapping_id', table_name='partner_activity')
    op.drop_index('ix_partner_cu_partner_id', table_name='partner_activity')
    op.drop_index('ix_partner_cu_village_id', table_name='partner_activity')
    op.drop_column('partner_activity', 'iccm_components')
    op.add_column('session_attendance', sa.Column('training_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_session_attendance_training_id'), 'session_attendance', ['training_id'], unique=False)
    op.create_foreign_key(None, 'session_attendance', 'training', ['training_id'], ['id'])
    op.create_index(op.f('ix_subcounty_countyID'), 'subcounty', ['countyID'], unique=False)
    op.create_index(op.f('ix_subcounty_mappingId'), 'subcounty', ['mappingId'], unique=False)
    op.drop_index('ix_subcounty_countyID', table_name='subcounty')
    op.drop_index('ix_subcounty_mappingId', table_name='subcounty')
    op.add_column('training', sa.Column('date_commenced', sa.Numeric(), nullable=True))
    op.add_column('training', sa.Column('date_completed', sa.Numeric(), nullable=True))
    op.create_index(op.f('ix_training_trainers_trainer_id'), 'training_trainers', ['trainer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_trainers_trainer_id'), table_name='training_trainers')
    op.drop_column('training', 'date_completed')
    op.drop_column('training', 'date_commenced')
    op.create_index('ix_subcounty_mappingId', 'subcounty', ['mappingId'], unique=False)
    op.create_index('ix_subcounty_countyID', 'subcounty', ['countyID'], unique=False)
    op.drop_index(op.f('ix_subcounty_mappingId'), table_name='subcounty')
    op.drop_index(op.f('ix_subcounty_countyID'), table_name='subcounty')
    op.drop_constraint(None, 'session_attendance', type_='foreignkey')
    op.drop_index(op.f('ix_session_attendance_training_id'), table_name='session_attendance')
    op.drop_column('session_attendance', 'training_id')
    op.add_column('partner_activity', sa.Column('iccm_components', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('ix_partner_cu_village_id', 'partner_activity', ['village_id'], unique=False)
    op.create_index('ix_partner_cu_partner_id', 'partner_activity', ['partner_id'], unique=False)
    op.create_index('ix_partner_cu_mapping_id', 'partner_activity', ['mapping_id'], unique=False)
    op.create_index('ix_partner_cu_community_unit_id', 'partner_activity', ['community_unit_id'], unique=False)
    op.create_index('ix_partner_cu_added_by', 'partner_activity', ['added_by'], unique=False)
    op.drop_index(op.f('ix_partner_activity_village_id'), table_name='partner_activity')
    op.drop_index(op.f('ix_partner_activity_partner_id'), table_name='partner_activity')
    op.drop_index(op.f('ix_partner_activity_mapping_id'), table_name='partner_activity')
    op.drop_index(op.f('ix_partner_activity_community_unit_id'), table_name='partner_activity')
    op.drop_index(op.f('ix_partner_activity_added_by'), table_name='partner_activity')
    # ### end Alembic commands ###
