"""Add Trainee Status table

Revision ID: 91cdf4665fbc
Revises: 200c406c9b7a
Create Date: 2018-03-19 10:29:17.762228

"""

# revision identifiers, used by Alembic.
revision = '91cdf4665fbc'
down_revision = '200c406c9b7a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    status_table = op.create_table('trainee_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('readonly', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('country', sa.String(length=20), nullable=False),
    sa.Column('client_time', sa.Numeric(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], [u'users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainee_status_created_by'), 'trainee_status', ['created_by'], unique=False)
    op.add_column(u'trainees', sa.Column('trainee_status', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trainees', 'trainee_status', ['trainee_status'], ['id'])
    
    ## Some seed data:
    op.bulk_insert(status_table, [
        {'id':1, 'name':'Ongoing', 'archived':0, 'readonly':1, 'country':'KE'},
        {'id':2, 'name':'Dropped', 'archived':0, 'readonly':1, 'country':'KE'}
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trainees', type_='foreignkey')
    op.drop_column(u'trainees', 'trainee_status')
    op.drop_index(op.f('ix_trainee_status_created_by'), table_name='trainee_status')
    op.drop_table('trainee_status')
    # ### end Alembic commands ###
