"""community unit made id primary key

Revision ID: 9b6138c9af17
Revises: bfcd024a1982
Create Date: 2018-07-12 16:11:27.281763

"""

# revision identifiers, used by Alembic.
revision = '9b6138c9af17'
down_revision = 'bfcd024a1982'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_community_unit_id'), 'community_unit', ['id'], unique=False)
    op.create_foreign_key(None, 'partner_activity', 'community_unit', ['community_unit_id'], ['id'])
    op.create_foreign_key(None, 'village', 'community_unit', ['community_unit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'village', type_='foreignkey')
    op.drop_constraint(None, 'partner_activity', type_='foreignkey')
    op.drop_index(op.f('ix_community_unit_id'), table_name='community_unit')
    # ### end Alembic commands ###
