"""Convert ExamResult ID to UUID

Revision ID: 9be7d90b854f
Revises: 40b608279fe1
Create Date: 2018-07-20 14:56:55.188664

"""

# revision identifiers, used by Alembic.
revision = '9be7d90b854f'
down_revision = '40b608279fe1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_community_unit_id'), 'community_unit', ['id'], unique=False)
    op.create_index(op.f('ix_exam_results_id'), 'exam_results', ['id'], unique=False)
    op.create_foreign_key(None, 'partner_activity', 'community_unit', ['community_unit_id'], ['id'])
    op.create_foreign_key(None, 'village', 'community_unit', ['community_unit_id'], ['id'])
    op.alter_column(u'exam_results',
                    'id',
                    type_=sa.String(length=64),
                    existing_type=sa.INTEGER()
                    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'village', type_='foreignkey')
    op.drop_constraint(None, 'partner_activity', type_='foreignkey')
    op.drop_index(op.f('ix_exam_results_id'), table_name='exam_results')
    op.drop_index(op.f('ix_community_unit_id'), table_name='community_unit')
    
    # ### end Alembic commands ###
