"""empty message

Revision ID: a947805790c
Revises: None
Create Date: 2017-06-19 11:38:56.942455

"""

# revision identifiers, used by Alembic.
revision = 'a947805790c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('niaje', sa.Integer(), nullable=True))
    op.add_column('application', sa.Column('testing', sa.Integer(), nullable=True))
    op.add_column('education', sa.Column('country', sa.String(length=45), server_default=sa.text(u"'UG'"), nullable=True))
    op.add_column('education', sa.Column('hierachy', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True))
    op.add_column('education', sa.Column('level_type', sa.String(length=45), nullable=True))
    op.create_index(op.f('ix_exams_recruitment'), 'exams', ['recruitment'], unique=False)
    op.drop_index('ix_exams_recruitment_id', table_name='exams')
    op.create_index(op.f('ix_gps_data_chp_phone'), 'gps_data', ['chp_phone'], unique=False)
    op.create_foreign_key(None, 'gps_data', 'application', ['chp_phone'], ['id'])
    op.create_index(op.f('ix_interviews_recruitment'), 'interviews', ['recruitment'], unique=False)
    op.drop_index('ix_interviews_recruitment_id', table_name='interviews')
    op.alter_column('location', 'country',
               existing_type=sa.VARCHAR(length=45),
               nullable=False,
               existing_server_default=sa.text(u"'UG'::character varying"))
    op.create_index(op.f('ix_registrations_education'), 'registrations', ['education'], unique=False)
    op.create_foreign_key(None, 'registrations', 'education', ['education'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.drop_index(op.f('ix_registrations_education'), table_name='registrations')
    op.alter_column('location', 'country',
               existing_type=sa.VARCHAR(length=45),
               nullable=False,
               existing_server_default=sa.text(u"'UG'::character varying"))
    op.create_index('ix_interviews_recruitment_id', 'interviews', ['recruitment'], unique=False)
    op.drop_index(op.f('ix_interviews_recruitment'), table_name='interviews')
    op.drop_constraint(None, 'gps_data', type_='foreignkey')
    op.drop_index(op.f('ix_gps_data_chp_phone'), table_name='gps_data')
    op.create_index('ix_exams_recruitment_id', 'exams', ['recruitment'], unique=False)
    op.drop_index(op.f('ix_exams_recruitment'), table_name='exams')
    op.drop_column('education', 'level_type')
    op.drop_column('education', 'hierachy')
    op.drop_column('education', 'country')
    op.drop_column('application', 'testing')
    op.drop_column('application', 'niaje')
    ### end Alembic commands ###
