"""branch migration-recruitment-cohort

Revision ID: ac5ea11816da
Revises: 1355458f54fc
Create Date: 2019-02-05 16:44:29.138480

"""

# revision identifiers, used by Alembic.
revision = 'ac5ea11816da'
down_revision = '1355458f54fc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch', sa.Column('country', sa.String(length=64), nullable=True))
    op.add_column('branch', sa.Column('county_id', sa.String(length=65), nullable=True))
    op.add_column('branch', sa.Column('subcounty_id', sa.String(length=65), nullable=True))
    op.drop_constraint(u'branch_mapping_id_fkey', 'branch', type_='foreignkey')
    op.drop_column('branch', 'mapping_id')
    op.drop_column('branch', 'branch_code')
    op.add_column('recruitments', sa.Column('cohort_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recruitments', 'cohort', ['cohort_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recruitments', type_='foreignkey')
    op.drop_column('recruitments', 'cohort_id')
    op.add_column('branch', sa.Column('branch_code', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.add_column('branch', sa.Column('mapping_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_foreign_key(u'branch_mapping_id_fkey', 'branch', 'mapping', ['mapping_id'], ['id'])
    op.drop_column('branch', 'subcounty_id')
    op.drop_column('branch', 'county_id')
    op.drop_column('branch', 'country')
    # ### end Alembic commands ###
