"""add archived to Link Facility

Revision ID: bb56403c2327
Revises: 5f2cf558752e
Create Date: 2017-08-16 08:52:11.791357

"""

# revision identifiers, used by Alembic.
revision = 'bb56403c2327'
down_revision = '5f2cf558752e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link_facility', sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_subcounty_mappingId', 'subcounty', ['mappingId'], unique=False)
    op.create_index('ix_subcounty_countyID', 'subcounty', ['countyID'], unique=False)
    op.drop_index(op.f('ix_subcounty_mappingId'), table_name='subcounty')
    op.drop_index(op.f('ix_subcounty_countyID'), table_name='subcounty')
    op.drop_column('link_facility', 'archived')
    # ### end Alembic commands ###
