"""Added other field to three entities


Revision ID: c076964f88ea
Revises: 6375f8c835b3
Create Date: 2018-10-11 16:08:25.243943

"""

# revision identifiers, used by Alembic.
revision = 'c076964f88ea'
down_revision = '6375f8c835b3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_unit', sa.Column('other', sa.Text(), server_default=sa.text(u"'{}'"), nullable=True))
    op.add_column('link_facility', sa.Column('other', sa.Text(), server_default=sa.text(u"'{}'"), nullable=True))
    op.add_column('partner_activity', sa.Column('other', sa.Text(), server_default=sa.text(u"'{}'"), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partner_activity', 'other')
    op.drop_column('link_facility', 'other')
    op.drop_column('community_unit', 'other')
    # ### end Alembic commands ###
