"""add other field to registration

Revision ID: cb0bf8167ff4
Revises: c076964f88ea
Create Date: 2018-12-03 08:09:58.115829

"""

# revision identifiers, used by Alembic.
revision = 'cb0bf8167ff4'
down_revision = 'c076964f88ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('other', sa.Text(), server_default=sa.text(u"'{}'"), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'other')
    # ### end Alembic commands ###
