"""Added passmark to ExamTraining model

Revision ID: d37f87222694
Revises: 057f277c3729
Create Date: 2018-06-12 15:40:22.187588

"""

# revision identifiers, used by Alembic.
revision = 'd37f87222694'
down_revision = '057f277c3729'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_trainings', sa.Column('passmark', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_trainings', 'passmark')
    # ### end Alembic commands ###
