"""add archived to community unit

Revision ID: dbe50cfb9d16
Revises: bb56403c2327
Create Date: 2017-08-16 10:49:02.118430

"""

# revision identifiers, used by Alembic.
revision = 'dbe50cfb9d16'
down_revision = 'bb56403c2327'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_unit', sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_subcounty_mappingId', 'subcounty', ['mappingId'], unique=False)
    op.create_index('ix_subcounty_countyID', 'subcounty', ['countyID'], unique=False)
    op.drop_index(op.f('ix_subcounty_mappingId'), table_name='subcounty')
    op.drop_index(op.f('ix_subcounty_countyID'), table_name='subcounty')
    op.drop_column('community_unit', 'archived')
    # ### end Alembic commands ###
