"""Added exam unlock code and changed question size

Revision ID: e625e9edaa35
Revises: 8d17beb57761
Create Date: 2018-06-27 12:18:08.658152

"""

# revision identifiers, used by Alembic.
from random import randint

revision = 'e625e9edaa35'
down_revision = '8d17beb57761'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_exams', sa.Column('unlock_code', sa.Integer(), nullable=True))
    op.alter_column(u'questions', 'question', type_=sa.TEXT())
    op.alter_column(u'question_choices', 'question_choice', type_=sa.VARCHAR(256))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'question_choices', 'question_choice', type_=sa.VARCHAR(64))
    op.alter_column(u'questions', 'question',type_=sa.VARCHAR(255))
    op.drop_column('training_exams', 'unlock_code')
    # ### end Alembic commands ###
