"""add ICCM Components table

Revision ID: ea02994caa3f
Revises: 0cc6576e18f0
Create Date: 2017-08-17 16:47:19.237892

"""

# revision identifiers, used by Alembic.
revision = 'ea02994caa3f'
down_revision = '0cc6576e18f0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iccm_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_name', sa.String(length=128), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('client_time', sa.Numeric(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('status', sa.String(length=64), server_default=sa.text(u"'draft'"), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], [u'users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iccm_components_added_by'), 'iccm_components', ['added_by'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_iccm_components_added_by'), table_name='iccm_components')
    op.drop_table('iccm_components')
    # ### end Alembic commands ###
