"""Add Education Levels

Revision ID: eb4c105667a
Revises: 1b90e26ba1d3
Create Date: 2017-06-19 15:30:09.706511

"""

# revision identifiers, used by Alembic.
revision = 'eb4c105667a'
down_revision = '1b90e26ba1d3'

from alembic import op
from sqlalchemy import table
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###

    op.add_column('application', sa.Column('niaje', sa.Integer(), nullable=True))
    op.add_column('application', sa.Column('testing', sa.Integer(), nullable=True))
    op.add_column('education', sa.Column('country', sa.String(length=45), server_default=sa.text(u"'UG'"), nullable=True))
    op.add_column('education', sa.Column('hierachy', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True))
    op.add_column('education', sa.Column('level_type', sa.String(length=45), nullable=True))
    education_table = table('education')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'testing')
    op.drop_column('application', 'niaje')
    ### end Alembic commands ###
