"""add training, trainig_sessions, training_trainers models

Revision ID: ec0f389b6dbd
Revises: ea02994caa3f
Create Date: 2017-09-05 15:10:46.484916

"""

# revision identifiers, used by Alembic.
revision = 'ec0f389b6dbd'
down_revision = 'ea02994caa3f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_session_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_name', sa.String(length=20), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=20), nullable=False),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('client_time', sa.Numeric(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], [u'users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_roles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('role_name', sa.String(length=20), nullable=True),
                    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
                    sa.Column('readonly', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
                    sa.Column('country', sa.String(length=20), nullable=False),
                    sa.Column('client_time', sa.Numeric(), nullable=True),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('date_created', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['created_by'], [u'users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_training_roles_created_by'), 'training_roles', ['created_by'], unique=False)
    
    op.create_index(op.f('ix_training_session_type_added_by'), 'training_session_type', ['added_by'], unique=False)
    op.create_index(op.f('ix_training_session_type_created_by'), 'training_session_type', ['created_by'], unique=False)
    op.create_table('training_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('readonly', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('country', sa.String(length=20), nullable=False),
    sa.Column('client_time', sa.Numeric(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], [u'users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_status_created_by'), 'training_status', ['created_by'], unique=False)
    op.create_table('training',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('training_name', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('subcounty_id', sa.String(length=64), nullable=True),
    sa.Column('ward_id', sa.String(length=64), nullable=True),
    sa.Column('district', sa.String(length=45), nullable=True),
    sa.Column('recruitment_id', sa.String(length=64), nullable=True),
    sa.Column('parish_id', sa.String(length=64), nullable=True),
    sa.Column('lat', sa.Float(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('lon', sa.Float(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('client_time', sa.Numeric(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['county_id'], [u'ke_county.id'], ),
    sa.ForeignKeyConstraint(['created_by'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], [u'location.id'], ),
    sa.ForeignKeyConstraint(['parish_id'], [u'parish.id'], ),
    sa.ForeignKeyConstraint(['recruitment_id'], [u'recruitments.id'], ),
    sa.ForeignKeyConstraint(['status'], [u'training_status.id'], ),
    sa.ForeignKeyConstraint(['subcounty_id'], [u'subcounty.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], [u'ward.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_county_id'), 'training', ['county_id'], unique=False)
    op.create_index(op.f('ix_training_created_by'), 'training', ['created_by'], unique=False)
    op.create_index(op.f('ix_training_location_id'), 'training', ['location_id'], unique=False)
    op.create_index(op.f('ix_training_parish_id'), 'training', ['parish_id'], unique=False)
    op.create_index(op.f('ix_training_recruitment_id'), 'training', ['recruitment_id'], unique=False)
    op.create_index(op.f('ix_training_status'), 'training', ['status'], unique=False)
    op.create_index(op.f('ix_training_subcounty_id'), 'training', ['subcounty_id'], unique=False)
    op.create_index(op.f('ix_training_ward_id'), 'training', ['ward_id'], unique=False)
    op.create_table('training_session',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('training_session_type_id', sa.Integer(), nullable=True),
    sa.Column('training_id', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=20), nullable=True),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('client_time', sa.Numeric(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['training_id'], [u'training.id'], ),
    sa.ForeignKeyConstraint(['training_session_type_id'], [u'training_session_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_training_session_created_by'), 'training_session', ['created_by'], unique=False)
    op.create_index(op.f('ix_training_session_training_id'), 'training_session', ['training_id'], unique=False)
    op.create_index(op.f('ix_training_session_training_session_type_id'), 'training_session', ['training_session_type_id'], unique=False)
    op.create_table('training_trainers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_id', sa.String(length=64), nullable=True),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=20), nullable=True),
    sa.Column('client_time', sa.Numeric(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('training_role_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['training_role_id'], [u'training_roles.id'], ),
    sa.ForeignKeyConstraint(['training_id'], [u'training.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_trainers_created_by'), 'training_trainers', ['created_by'], unique=False)
    op.create_index(op.f('ix_training_trainers_training_role_id'), 'training_trainers', ['training_role_id'], unique=False)
    op.create_index(op.f('ix_training_trainers_training_id'), 'training_trainers', ['training_id'], unique=False)
    op.create_table('session_attendance',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('training_session_id', sa.String(length=64), nullable=True),
    sa.Column('trainee_id', sa.String(length=64), nullable=True),
    sa.Column('training_session_type_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=20), nullable=False),
    sa.Column('attended', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('client_time', sa.Numeric(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('archived', sa.Integer(), server_default=sa.text(u"'0'"), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['trainee_id'], [u'registrations.id'], ),
    sa.ForeignKeyConstraint(['training_session_id'], [u'training_session.id'], ),
    sa.ForeignKeyConstraint(['training_session_type_id'], [u'training_session_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_attendance_created_by'), 'session_attendance', ['created_by'], unique=False)
    op.create_index(op.f('ix_session_attendance_trainee_id'), 'session_attendance', ['trainee_id'], unique=False)
    op.create_index(op.f('ix_session_attendance_training_session_id'), 'session_attendance', ['training_session_id'], unique=False)
    op.create_index(op.f('ix_session_attendance_training_session_type_id'), 'session_attendance', ['training_session_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_attendance_training_session_type_id'), table_name='session_attendance')
    op.drop_index(op.f('ix_session_attendance_training_session_id'), table_name='session_attendance')
    op.drop_index(op.f('ix_session_attendance_trainee_id'), table_name='session_attendance')
    op.drop_index(op.f('ix_session_attendance_created_by'), table_name='session_attendance')
    op.drop_table('session_attendance')
    op.drop_index(op.f('ix_training_trainers_training_id'), table_name='training_trainers')
    op.drop_index(op.f('ix_training_trainers_trainer_id'), table_name='training_trainers')
    op.drop_index(op.f('ix_training_trainers_created_by'), table_name='training_trainers')
    op.drop_index(op.f('ix_training_trainers_training_role_id'), table_name='training_trainers')
    op.drop_table('training_trainers')
    op.drop_index(op.f('ix_training_session_training_session_type_id'), table_name='training_session')
    op.drop_index(op.f('ix_training_session_training_id'), table_name='training_session')
    op.drop_index(op.f('ix_training_session_created_by'), table_name='training_session')
    op.drop_table('training_session')
    op.drop_index(op.f('ix_training_ward_id'), table_name='training')
    op.drop_index(op.f('ix_training_subcounty_id'), table_name='training')
    op.drop_index(op.f('ix_training_status'), table_name='training')
    op.drop_index(op.f('ix_training_recruitment_id'), table_name='training')
    op.drop_index(op.f('ix_training_parish_id'), table_name='training')
    op.drop_index(op.f('ix_training_location_id'), table_name='training')
    op.drop_index(op.f('ix_training_created_by'), table_name='training')
    op.drop_index(op.f('ix_training_county_id'), table_name='training')
    op.drop_table('training')
    op.drop_index(op.f('ix_training_status_created_by'), table_name='training_status')
    op.drop_table('training_status')
    op.drop_index(op.f('ix_training_session_type_created_by'), table_name='training_session_type')
    op.drop_index(op.f('ix_training_session_type_added_by'), table_name='training_session_type')
    op.drop_table('training_session_type')
    op.drop_index(op.f('ix_training_roles_created_by'), table_name='training_roles')
    op.drop_table('training_roles')
    
    # ### end Alembic commands ###